-- MySQL Script generated by MySQL Workbench
-- mié 15 jun 2022 14:06:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema school
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school` ;
USE `school` ;

-- -----------------------------------------------------
-- Table `school`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`users` (
  `user_id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `last_names` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `birth_date` DATE NOT NULL,
  `phone` VARCHAR(12) NOT NULL,
  `user_role` VARCHAR(10) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`signatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`signatures` (
  `signature_id` INT NOT NULL AUTO_INCREMENT,
  `grade` VARCHAR(3) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `teacher_id` VARCHAR(64) NOT NULL,
  `signature_year` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`signature_id`),
  INDEX `fk_users_signatures_teacher_id_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_signatures_teacher_id`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `school`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`pensum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`pensum` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `period` INT NOT NULL,
  `signature_id` INT NOT NULL,
  `max_rating` FLOAT NOT NULL DEFAULT 5,
  `min_rating` FLOAT NOT NULL DEFAULT 3.5,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rating_id`),
  INDEX `fk_signatures_pensum_signature_id_idx` (`signature_id` ASC) VISIBLE,
  CONSTRAINT `fk_signatures_pensum_signature_id`
    FOREIGN KEY (`signature_id`)
    REFERENCES `school`.`signatures` (`signature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`signature_link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`signature_link` (
  `signature_link_id` INT NOT NULL,
  `signature_id` INT NOT NULL,
  `student_id` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`signature_link_id`),
  INDEX `fk_signatures_signature_link_signature_id_idx` (`signature_id` ASC) VISIBLE,
  INDEX `fk_users_signature_link_student_id_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_signatures_signature_link_signature_id`
    FOREIGN KEY (`signature_id`)
    REFERENCES `school`.`signatures` (`signature_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_signature_link_student_id`
    FOREIGN KEY (`student_id`)
    REFERENCES `school`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`ratings` (
  `rating` FLOAT NOT NULL,
  `rating_id` INT NOT NULL,
  `signature_link_id` INT NOT NULL,
  INDEX `fk_signature_link_ratings_signature_link_id_idx` (`signature_link_id` ASC) VISIBLE,
  INDEX `fk_pensum_ratings_rating_id_idx` (`rating_id` ASC) VISIBLE,
  CONSTRAINT `fk_signature_link_ratings_signature_link_id`
    FOREIGN KEY (`signature_link_id`)
    REFERENCES `school`.`signature_link` (`signature_link_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pensum_ratings_rating_id`
    FOREIGN KEY (`rating_id`)
    REFERENCES `school`.`pensum` (`rating_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `school`.`absences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `school`.`absences` (
  `signature_link_id` INT NOT NULL,
  `justified` TINYINT NOT NULL,
  `justification` VARCHAR(255) NULL,
  INDEX `fk_signature_link_absences_signature_link_id_idx` (`signature_link_id` ASC) VISIBLE,
  CONSTRAINT `fk_signature_link_absences_signature_link_id`
    FOREIGN KEY (`signature_link_id`)
    REFERENCES `school`.`signature_link` (`signature_link_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
